version: '3'
services:
    ranksystem:
      build: .
      restart: always
      volumes:
       - ./tsn/configs:/app/other
       - ./tsn/logs:/app/logs

    ranksystem-db:
      image: mariadb:10.6
      restart: always
      environment:
        MARIADB_RANDOM_ROOT_PASSWORD: 1
        MARIADB_USER: ${MARIADB_USER}
        MARIADB_PASSWORD: ${MARIADB_PASSWORD}
        MARIADB_DATABASE: ${MARIADB_DATABASE}
      volumes:
        - ./tsn/db/:/var/lib/mysql
